Lab5/App/Controllers/DataController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using System.Security.Cryptography;

namespace App.Controllers
{
    public class DataController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;
        private readonly string _apiUrl = "http://localhost:5047";
        public DataController(IHttpClientFactory httpClientFactory) 
        {
            _httpClientFactory = httpClientFactory;
        }

        public async Task<JArray> GetObjects(string controller, string? version = null)
        {
            var client = _httpClientFactory.CreateClient();
            HttpResponseMessage response = null;

            if (!string.IsNullOrEmpty(version))
            {
                response = await client.GetAsync($"{_apiUrl}/api/v{version}/{controller}");
            }
            else
            {
                response = await client.GetAsync($"{_apiUrl}/api/{controller}");
            }

            if (response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync();
                var copies = JArray.Parse(content);
                return copies;
            }

            return new JArray();
        }

        public async Task<JObject> GetObject(string controller, string? version = null, string? string_id = null, int? int_id = null)
        {
            var client = _httpClientFactory.CreateClient();
            HttpResponseMessage response = null;

            if (!string.IsNullOrEmpty(string_id) && !string.IsNullOrEmpty(version))
            {
                response = await client.GetAsync($"{_apiUrl}/api/v{version}/{controller}/{string_id}");
            }
            else if (int_id.HasValue && !string.IsNullOrEmpty(version)) 
            { 
                response = await client.GetAsync($"{_apiUrl}/api/v{version}/{controller}/{int_id}");
            }
            else
            {
                response = await client.GetAsync($"{_apiUrl}/api/{controller}/{int_id}");
            }

            if (response != null && response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync();
                var copy = JObject.Parse(content);
                return copy;
            }

            return new JObject();
        }

        public async Task<IActionResult> BookingStatusesV1()
        {
            var statuses = await GetObjects("BookingStatus", version: "1.0");

            if (statuses != null && statuses.Count > 0) 
            {
                return View(statuses);
            }

            return View(new JArray());
        }

        public async Task<IActionResult> BookingStatusesV2()
        {
            var statuses = await GetObjects("BookingStatus", version: "2.0");

            if (statuses != null && statuses.Count > 0)
            {
                return View(statuses);
            }

            return View(new JArray());
        }

        public async Task<IActionResult> BookingStatusDetailsV1(string id)
        {
            var bookingStatus = await GetObject("BookingStatus", string_id: id, version: "1.0");

            if (bookingStatus != null  && bookingStatus.HasValues) 
            { 
                return View(bookingStatus); 
            }

            return NotFound();
        }

        public async Task<IActionResult> BookingStatusDetailsV2(string id)
        {
            var bookingStatus = await GetObject("BookingStatus", string_id: id, version: "2.0");

            if (bookingStatus != null && bookingStatus.HasValues)
            {
                return View(bookingStatus);
            }

            return NotFound();
        }

        public async Task<IActionResult> Vehicles()
        {
            var vehicles = await GetObjects("Vehicle");

            if (vehicles != null && vehicles.Count > 0)
            {
                return View(vehicles);
            }

            return View(new JArray());
        }

        public async Task<IActionResult> VehicleDetails(string regNumber)
        {
            var vehicle = await GetObject("Vehicle", string_id: regNumber);

            if (vehicle != null && vehicle.HasValues)
            {
                return View(vehicle);
            }

            return NotFound();
        }

        public async Task<IActionResult> Bookings()
        {
            var bookings = await GetObjects("Booking");

            if (bookings != null && bookings.Count > 0)
            {
                return View(bookings);
            }

            return View(new JArray());
        }

        public async Task<IActionResult> BookingDetails(int bookingId)
        {
            var booking = await GetObject("Booking", int_id: bookingId);

            if (booking != null && booking.HasValues)
            {
                return View(booking);
            }

            return NotFound();
        }


        public async Task<IActionResult> SearchBookings(DateTime? dateFrom, DateTime? dateTo, List<string> statusCodes, string? startVehicleReg = null, string? endVehicleReg = null)
        {
            var client = _httpClientFactory.CreateClient();

            var queryParam = new List<string>();

            if (dateFrom.HasValue) queryParam.Add($"dateFrom={dateFrom.Value:O}");
            if (dateTo.HasValue) queryParam.Add($"dateTo={dateTo.Value:O}");
            if (statusCodes != null && statusCodes.Any())
            {
                foreach (var code in statusCodes)
                {
                    queryParam.Add($"statusCodes={code}");
                }
            }
            if (!String.IsNullOrEmpty(startVehicleReg)) queryParam.Add($"startVehicleReg={startVehicleReg}");
            if (!String.IsNullOrEmpty(endVehicleReg)) queryParam.Add($"endVehicleReg={endVehicleReg}");

            var query = string.Join("&", queryParam);
            var response = await client.GetAsync($"{_apiUrl}/api/Booking/search?{query}");

            if (response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync();
                var searchResults = JArray.Parse(content);
                return View(searchResults);
            }

            return View(new JArray());
        }
    }
}

Lab5/App/Controllers/HomeController.cs
using App.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace App.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult DisplayLab(string lab)
        {
            var accessToken = HttpContext.Session.GetString("AccessToken");
            ViewBag.AccessToken = accessToken;

            if (string.IsNullOrEmpty(accessToken)) 
            {
                return Unauthorized("Ви не увійшли в систему. Будь ласка, увійдіть.");
            }

            switch (lab)
            {
                case ("lab1"):
                    return View("Lab1");

                case ("lab2"):
                    return View("Lab2");

                case ("lab3"):
                    return View("Lab3");

                default:
                    return NotFound();
            }
        }

        [HttpPost]
        public async Task<IActionResult> RunLabs(IFormFile inputFile, string pathProject)
        {
            if (inputFile == null || inputFile.Length == 0)
            {
                return BadRequest("Файл не був завантажен.");
            }

            var tempInputFilePath = Path.Combine(Path.GetTempPath(), "INPUT.TXT");
            using (var stream = new FileStream(tempInputFilePath, FileMode.Create))
            {
                await inputFile.CopyToAsync(stream);
            }

            var tempOutputFilePath = Path.Combine(Path.GetTempPath(), "OUTPUT.TXT");

            Environment.SetEnvironmentVariable("INPUT_FILE", tempInputFilePath);
            Environment.SetEnvironmentVariable("OUTPUT_FILE", tempOutputFilePath);

            string result = MyLibrary.LabsLibrary.ExecuteLabs(pathProject);

            if (System.IO.File.Exists(tempOutputFilePath))
            {
                result += "\nРезультати з OUTPUT.TXT:\n";
                result += await System.IO.File.ReadAllTextAsync(tempOutputFilePath);
            }

            ViewData["Result"] = result;

            return View("LabsResult");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Lab5/App/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    
}

<div>
    <h2>Оберіть лабораторну</h2>
    
    <ul>
        <li>
            <a asp-action="DisplayLab" asp-route-lab="lab1">Lab 1</a>
        </li>
        <li>
            <a asp-action="DisplayLab" asp-route-lab="lab2">Lab 2</a>
        </li>
        <li>
            <a asp-action="DisplayLab" asp-route-lab="lab3">Lab 3</a>
        </li>
    </ul>

    <h2>Робота з БД</h2>
    <p><a asp-controller="Data" asp-action="BookingStatusesV1">Список Booking Status v1</a></p>
    <p><a asp-controller="Data" asp-action="BookingStatusesV2">Список Booking Status v2</a></p>
    <p><a asp-controller="Data" asp-action="Vehicles">Список Vehicles</a></p>
    <p><a asp-controller="Data" asp-action="Bookings">Список центральної таблиці Booking</a></p>
    
    <h1>Пошук Bookings</h1>

    <form method="get" asp-controller="Data" asp-action="SearchBookings">
        <div>
            <label for="dateFrom">From Date:</label>
            <input type="datetime-local" id="dateFrom" name="dateFrom" />
        </div>
        <div>
            <label for="dateTo">To Date:</label>
            <input type="datetime-local" id="dateTo" name="dateTo" />
        </div>
        <div>
            <label for="statusCodes">Status Codes:</label>
            <select id="statusCodes" name="statusCodes" multiple>
                <option value="PND">Pending</option>
                <option value="CMP">Completed</option>
                <option value="CNC">Cancelled</option>
                <option value="CON">Confirmed</option>
                <option value="NEW">New Boook</option>
            </select>
        </div>
        <div>
            <label for="startVehicleReg">Start Vehicle Reg:</label>
            <input type="text" id="startVehicleReg" name="startVehicleReg" />
        </div>
        <div>
            <label for="endVehicleReg">End Vehicle Reg:</label>
            <input type="text" id="endVehicleReg" name="endVehicleReg" />
        </div>
        <button type="submit">Search</button>
    </form>

    <hr />

</div>

Lab5/App/Views/Home/Lab1.cshtml
@{
    ViewData["Title"] = "Lab 1";
}

<h2>Lab 1</h2>

<div>
    <p>
        <h3>Завдання</h3>
        Толик вигадав нову технологію програмування. Він хоче умовити друзів використати її. Але все не так просто. i-й друг погодиться використовувати технологію Толіка, 
        якщо його авторитет буде не меншим за ai (авторитет виражається цілим числом). Як тільки він почне її використовувати, до авторитету Толіка додасться число bi 
        (трапляються люди, у яких bi < 0). Допоможіть Толіку наставити на правдивий шлях якомога більше своїх друзів.

        <h3>Приклад</h3>
        <h4>INPUT.TXT</h4>
        <pre>
    5 1
    1 3
    6 -5
    6 -4
    2 2
    2 -1
        </pre>
        <h4>OUTPUT.TXT</h4>
        <pre>
    4
    1 4 3 5
        </pre>
    </p>



</div>

<form asp-action="RunLabs" asp-controller="Home" method="post" enctype="multipart/form-data">
    <div>
        <label for="inputFile"><strong>Завантажте файл INPUT.TXT:</strong></label>
        <input type="file" id="inputFile" name="inputFile" accept=".txt" required />
    </div>
    <input type="hidden" name="pathProject" value="@($"../../Lab1/App/App.csproj")" />
    <button type="submit">Виконати</button>
</form>

@if (ViewData["Result"] != null)
{
    <h3>Результати:</h3>
    <pre>@ViewData["Result"]</pre>
}

Lab5/App/Views/Home/Lab2.cshtml
@{
    ViewData["Title"] = "Lab 2";
}

<h2>Lab 2</h2>
<div>
    <p>
        <h3>Завдання</h3>
        Садівник посадив N дерев до одного ряду. Після посадки дерев садівнику їх потрібно пофарбувати. 
        У його розпорядженні є фарба трьох кольорів: біла, синя та помаранчева. Скільки способів фарбування дерев 
        є у нього, якщо жодні два сусідні дерева не можна фарбувати в однаковий колір?

        <h3>Приклад</h3>
        <h4>INPUT.TXT</h4>
        <pre>
    3
        </pre>
        <h4>OUTPUT.TXT</h4>
        <pre>
    12
        </pre>
    </p>



</div>

<form asp-action="RunLabs" asp-controller="Home" method="post" enctype="multipart/form-data">
    <div>
        <label for="inputFile">Завантажте файл INPUT.TXT:</label>
        <input type="file" id="inputFile" name="inputFile" accept=".txt" required />
    </div>
    <input type="hidden" name="pathProject" value="@($"../../Lab2/App/App.csproj")" />
    <button type="submit">Виконати</button>
</form>

@if (ViewData["Result"] != null)
{
    <h3>Результати:</h3>
    <pre>@ViewData["Result"]</pre>
}

Lab5/App/Views/Home/Lab3.cshtml
@{
    ViewData["Title"] = "Lab 3";
}

<h2>Lab 3</h2>
<div>
    <p>
        <h3>Завдання</h3>
        Хлопчику Севі дуже подобається колір індиго (це такий темно-синій колір). Сева всіляко намагається оточити себе речами цього кольору.
Незабаром Новий рік і Сева вирішив виготовити гірлянду з лампочками, щоб прикрасити їй свою кімнату. Він купив n патронів для лампочок і з'єднав (n-1)-ним дротом так, що 
в гірлянді не утворилося жодного замкнутого контуру. Його гірлянда, таким чином, з точки зору математики, є дерево. Для того щоб гірлянда була готова, залишилося зовсім небагато, 
треба тільки додати провід для підключення гірлянди в електричну мережу і вкрутити різнокольорові лампочки в патрони.Сева має лампочки трьох різних кольорів: синього, фіолетового 
та індиго. При цьому деякі патрони з міркувань краси не можна встановлювати лампочки певних кольорів. Також, з міркувань краси, у гірлянді не повинно бути двох лампочок одного кольору, які безпосередньо з'єднані проводом. Зрозуміло, Сева хоче, щоб у гірлянді було якнайбільше лампочок його улюбленого кольору.
Допоможіть Севі. Напишіть програму, яка знайде максимальну кількість лампочок кольору індиго, які можна встановити у зібрану гірлянду.


        <h3>Приклад</h3>
        <h4>INPUT.TXT</h4>
        <pre>
    3
    1 2
    2 3
    IB
    IV
    IB
        </pre>
        <h4>OUTPUT.TXT</h4>
        <pre>
    2
        </pre>
    </p>



</div>

<form asp-action="RunLabs" asp-controller="Home" method="post" enctype="multipart/form-data">
    <div>
        <label for="inputFile">Завантажте файл INPUT.TXT:</label>
        <input type="file" id="inputFile" name="inputFile" accept=".txt" required />
    </div>
    <input type="hidden" name="pathProject" value="@($"../../Lab3/App/App.csproj")" />
    <button type="submit">Виконати</button>
</form>

@if (ViewData["Result"] != null)
{
    <h3>Результати:</h3>
    <pre>@ViewData["Result"]</pre>
}

Lab5/App/Views/Home/LabsResult.cshtml
@{
    ViewData["Title"] = "Labs Result";
}

<h2>Результат виконання лабораторної роботи</h2>

<pre>@ViewData["Result"]</pre> 

<a asp-action="Index">Повернутися на головну</a>